version : "3"
services:
  db:
    build: dockerfile/db
    ports:
      - 3306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
      - "./dockerfile/db/my.cnf:/etc/alternatives/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - LANG=ja_JP.UTF-8

  app:
    build: dockerfile/app
    tty: true
    depends_on:
      - "db"
    environment:
      - MYSQL_PWD=pwd
      - DB_HOST=db
      - DB_NAME=test
      - DB_USER=user
      - DB_PWD=pwd
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
